spring:
  profiles:
    active: dev
# 端口项目名配置
server:
  port: 9100
  servlet:
    context-path: /next_document
# Mybatis mapper.xml位置配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
# jackson配置
jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    write-dates-as-timestamps: true
  default-property-inclusion: always