host:
  # 当前服务部署地址
  server-host: 172.16.176.65
spring:
  datasource:
# 自定义数据源, 在尝试创建数据库后再初始化
    my-datasource:
      jdbc-url: jdbc:mysql://localhost:3306/next_document?serverTimezone=GMT%2B8
      username: root
      password: 123456
# jdbc-url不指定数据库, 用于有限初始化尝试创建数据库
    database-initializer:
      jdbc-url: jdbc:mysql://localhost:3306?serverTimezone=GMT%2B8
      username: root
      password: 123456

# token配置
token:
  expiration:
    days: 7
  ignore-token-paths: /api/apply/config, /api/user/login
  need-token-paths:

# 日志级别配置
logging:
  level:
    com.gzl:
      debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9101
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always